### ISSUE TITLE
Use of Gamma distribution for SPEI calculations

### ISSUE THREAD

**Issue by s-m-t-c** [monocongo/climate_indices#190] opened 2018-10-03 06:59 UTC
I was just re-reading the key paper on SPEI<sup>1</sup> and noted the authors statement:
 
"Although the SPI can be calculated using a two-parameter distribution, such as the gamma distribution, a three-parameter distribution is needed to calculate the SPEI. In two-parameter distributions, the variable x has a lower boundary of zero (0>x<∞), whereas in three-parameter distributions,, _x_ can take values in the range (_y_>_x_<∞), where _y_ is the parameter of origin of the distribution; consequently, _x_ can have negative values, which are common in _D_ series." 

_D_ here refers to the difference in _D_<sub>i</sub> = _P_<sub>i</sub> - PET<sub>i</sub>

Building on this their R package<sup>2</sup> implements the gamma distribution as default for the SPI but uses a log-logistic distribution for SPEI. 

I've been using the gamma distribution in `climate_indices` for my SPEI calculations but their paper indicates that two-parameter distributions such as this shouldn't be implemented for the SPEI. Comparisons of my results using both Gamma and Pearson III distributions show pretty negligible differences between the two

Do you have any thoughts on this? 

Thanks in advance for your time and maintenance on this package!

<sup>1</sup>Vicente-Serrano, S. M., S. Beguería, et al. (2009). "A Multiscalar Drought Index Sensitive to Global Warming: The Standardized Precipitation Evapotranspiration Index." Journal of Climate 23(7): 1696-1718.

<sup>2</sup>https://cran.r-project.org/web/packages/SPEI/SPEI.pdf

**Comment by monocongo** [comment] 2018-10-03 13:36
This is an open issue, #106. Any assistance implementing this approach would be very helpful. Can we maybe put together a short summary of the math involved before focusing on the implementation? Thanks in advance for any help with this issue!

**Comment by monocongo** [comment] 2018-10-21 19:41
Closing since this is a duplicate of issue #106.

**Closed as completed by monocongo** 2018-10-21 19:41 UTC
